version: '3'
services:
  todo-list-frontend:
    image: ${CIRCLE_PROJECT_REPONAME}:${BRANCH_TAG}
    container_name: todo-list-frontend
    expose:
      - 80
    restart: always
    environment:
      - DEPLOYMENT={BRANCH_TAG}
      - GIT_SHA={SHA}

volumes:
  static_content: